# 应用名称
server:
  port: 9100
spring:
  application:
    name: server-consumer
  cloud:
    nacos:
      discovery:
        # Nacos认证信息
        username: nacos
        password: nacos
    sentinel:
      transport:
        dashboard: 192.168.0.237:8090
        clientIp: 192.168.17.27
      ## 默认情况下 Sentinel 会在客户端首次调用的时候进行初始化，开始向控制台发送心跳包
      ## 配置 sentinel.eager=true 时，取消Sentinel控制台懒加载功能
      eager: true
#
## Nacos帮助文档: https://nacos.io/zh-cn/docs/concepts.html
#
## 应用服务 WEB 访问端口
#
## Sentinel 控制台地址
## 取消Sentinel控制台懒加载


## 如果有多套网络，又无法正确获取本机IP，则需要使用下面的参数设置当前机器可被外部访问的IP地址，供admin控制台使用
## spring.cloud.sentinel.transport.client-ip=
#
management:
  endpoints:
    web:
      exposure:
        include: "*"
